<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="casp19083-PC" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="2020-03-19T17:46:23 IST" time="0.066" errors="0">
  <testcase name="test3" time="0.011" classname="firsttestngpackage.TestNGretryfailed">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at firsttestngpackage.TestNGretryfailed.test3(TestNGretryfailed.java:24)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.001" classname="firsttestngpackage.TestNGretryfailed"/>
  <testcase name="test1" time="0.0" classname="firsttestngpackage.TestNGretryfailed">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
